#!/usr/bin/env ruby
require '<%= project_name %>'

require 'optparse'

options = {:example_switch=>false,:show_help=>false}
opts = OptionParser.new do |o|
  o.banner = "Usage: #{File.basename($0)} [options] reponame\ne.g. #{File.basename($0)} the-perfect-gem"

  o.on('--example_parameter [EXAMPLE_PARAMETER]', 'TODO: put a description for the PARAMETER') do |example_parameter|
    # TODO: your logic here, below an example
    options[:example_parameter] = 'this is a parameter'
  end
  
  o.separator ""
  o.on("--switch-example", 'TODO: put a description for the SWITCH') do
    # TODO: your logic here, below an example
    self[:example_switch] = true
  end

  o.separator ""
  o.on_tail('-h', '--help', 'display this help and exit') do
    options[:show_help] = true
  end
end

begin
  opts.parse!(ARGV)
  # TODO: your code here
  # use options for your logic
rescue OptionParser::InvalidOption => e
  options[:invalid_argument] = e.message
end